### ISSUE TITLE
How to run multi account ?

### ISSUE THREAD

**Issue by nongdancryptos** [inanitynoupcase/getgrass#1]

**Comment by inanitynoupcase** [comment]
Clone the folder mate, each folder is a different account.

**Comment by nongdancryptos** [comment]
> Clone the folder mate, each folder is a different account.

Bro xem giúp mod lại app gradient của ông này được không, họ gắn virus vào rồi

https://github.com/Jaammerr/Gradient-Network-Bot

**Comment by inanitynoupcase** [comment]
> > Clone the folder mate, each folder is a different account.
> 
> Bro xem giúp mod lại app gradient của ông này được không, họ gắn virus vào rồi Cảm ơn bro
> 
> https://github.com/Jaammerr/Gradient-Network-Bot

ko phải virus đâu bro, người ta gắn bản quyền mà
